In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('kddcup99.csv')

In [3]:
dataset.head()

duration protocol_type service flag  src_bytes  dst_bytes  land  \
0         0           tcp    http   SF        181       5450     0   
1         0           tcp    http   SF        239        486     0   
2         0           tcp    http   SF        235       1337     0   
3         0           tcp    http   SF        219       1337     0   
4         0           tcp    http   SF        217       2032     0   

   wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0               0       0    0  ...                   9   
1               0       0    0  ...                  19   
2               0       0    0  ...                  29   
3               0       0    0  ...                  39   
4               0       0    0  ...                  49   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                     0.0   
1                     1.0                     0.0   
2                     1.0                     0.0   
3                     1.0                     0.0   
4                     1.0                     0.0   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.11                          0.0   
1                         0.05                          0.0   
2                         0.03                          0.0   
3                         0.03                          0.0   
4                         0.02                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate   label  
0                       0.0  normal  
1                       0.0  normal  
2                       0.0  normal  
3                       0.0  normal  
4                       0.0  normal  

[5 rows x 42 columns]

In [4]:
#Encoding the 'label' column such that Nomral : 0 and Everything Else is 1. 
#Using the replace method with a replace dictionary.

#Creating a copy of the dataset
df = pd.read_csv('kddcup99.csv')

df['label'].replace({
    'normal' : 0,
    'smurf' : 1,
    'neptune' : 1,
    'back' : 1,
    'satan' : 1,
    'ipsweep' : 1,
    'portsweep' : 1,
    'warezclient' : 1,
    'teardrop' : 1,
    'pod' : 1,
    'nmap' : 1,
    'guess_passwd' : 1,
    'buffer_overflow' : 1,
    'land' : 1,
    'warezmaster' : 1,
    'imap' : 1,
    'rootkit' : 1,
    'loadmodule' : 1,
    'ftp_write' : 1,
    'multihop' : 1,
    'phf' : 1,
    'perl' : 1,
    'spy' : 1
    
}, inplace = True)

df['label'].value_counts()

1    396743
0     97277
Name: label, dtype: int64

In [5]:
#Encoding the other categorical variables using Label Encoding from Scikit - Learn

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['protocol_type']  = le.fit_transform(df['protocol_type'])

df['service'] = le.fit_transform(df['service'])

df['flag'] = le.fit_transform(df['flag'])

df.head(20)

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0          0              1       22     9        181       5450     0   
1          0              1       22     9        239        486     0   
2          0              1       22     9        235       1337     0   
3          0              1       22     9        219       1337     0   
4          0              1       22     9        217       2032     0   
5          0              1       22     9        217       2032     0   
6          0              1       22     9        212       1940     0   
7          0              1       22     9        159       4087     0   
8          0              1       22     9        210        151     0   
9          0              1       22     9        212        786     0   
10         0              1       22     9        210        624     0   
11         0              1       22     9        177       1985     0   
12         0              1       22     9        222        773     0   
13         0              1       22     9        256       1169     0   
14         0              1       22     9        241        259     0   
15         0              1       22     9        260       1837     0   
16         0              1       22     9        241        261     0   
17         0              1       22     9        257        818     0   
18         0              1       22     9        233        255     0   
19         0              1       22     9        233        504     0   

    wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                0       0    0  ...                   9   
1                0       0    0  ...                  19   
2                0       0    0  ...                  29   
3                0       0    0  ...                  39   
4                0       0    0  ...                  49   
5                0       0    0  ...                  59   
6                0       0    0  ...                  69   
7                0       0    0  ...                  79   
8                0       0    0  ...                  89   
9                0       0    1  ...                  99   
10               0       0    0  ...                 109   
11               0       0    0  ...                 119   
12               0       0    0  ...                 129   
13               0       0    0  ...                 139   
14               0       0    0  ...                 149   
15               0       0    0  ...                 159   
16               0       0    0  ...                 169   
17               0       0    0  ...                 179   
18               0       0    0  ...                 189   
19               0       0    0  ...                 199   

    dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                      1.0                     0.0   
1                      1.0                     0.0   
2                      1.0                     0.0   
3                      1.0                     0.0   
4                      1.0                     0.0   
5                      1.0                     0.0   
6                      1.0                     0.0   
7                      1.0                     0.0   
8                      1.0                     0.0   
9                      1.0                     0.0   
10                     1.0                     0.0   
11                     1.0                     0.0   
12                     1.0                     0.0   
13                     1.0                     0.0   
14                     1.0                     0.0   
15                     1.0                     0.0   
16                     1.0                     0.0   
17                     1.0                     0.0   
18                     1.0                     0.0   
19                     1.0                     0.0   

    dst_host_same_src_port_rate  dst_host_srv_diff_ho

In [6]:
#Creating the Feature Set X and the Target Set Y using the GENETIC SET D Algorithm.


cols = ['src_bytes','dst_bytes','count','diff_srv_rate','dst_host_srv_count','dst_host_same_src_port_rate','label']
df1 = df[cols]
df1

src_bytes  dst_bytes  count  diff_srv_rate  dst_host_srv_count  \
0             181       5450      8            0.0                   9   
1             239        486      8            0.0                  19   
2             235       1337      8            0.0                  29   
3             219       1337      6            0.0                  39   
4             217       2032      6            0.0                  49   
...           ...        ...    ...            ...                 ...   
494015        310       1881      4            0.0                 255   
494016        282       2286      6            0.0                 255   
494017        203       1200      6            0.0                 255   
494018        291       1200      6            0.0                 255   
494019        219       1234      6            0.0                 255   

        dst_host_same_src_port_rate  label  
0                              0.11      0  
1                              0.05      0  
2                              0.03      0  
3                              0.03      0  
4                              0.02      0  
...                             ...    ...  
494015                         0.01      0  
494016                         0.17      0  
494017                         0.06      0  
494018                         0.04      0  
494019                         0.17      0  

[494020 rows x 7 columns]

## Checking for 10K Data

In [7]:
df2 = df1.head(10000)

In [8]:
df2

src_bytes  dst_bytes  count  diff_srv_rate  dst_host_srv_count  \
0           181       5450      8            0.0                   9   
1           239        486      8            0.0                  19   
2           235       1337      8            0.0                  29   
3           219       1337      6            0.0                  39   
4           217       2032      6            0.0                  49   
...         ...        ...    ...            ...                 ...   
9995       1032          0    511            0.0                 255   
9996       1032          0    511            0.0                 255   
9997       1032          0    511            0.0                 255   
9998       1032          0    511            0.0                 255   
9999       1032          0    511            0.0                 255   

      dst_host_same_src_port_rate  label  
0                            0.11      0  
1                            0.05      0  
2                            0.03      0  
3                            0.03      0  
4                            0.02      0  
...                           ...    ...  
9995                         1.00      1  
9996                         1.00      1  
9997                         1.00      1  
9998                         1.00      1  
9999                         1.00      1  

[10000 rows x 7 columns]

In [9]:
#Creating and the Feature and target Set for 10K Data
x1 = df2.iloc[:, :-1].values
y1 = df2.iloc[:, -1].values

In [10]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size = 0.25, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train1, y_train1)

SVC(random_state=0)

In [13]:
y_pred1 = classifier.predict(X_test1)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test1.reshape(len(y_test1),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test1, y_pred1)
print(cm)
accuracy_score(y_test1, y_pred1)

[[1939    0]
 [   1  560]]


0.9996

## Checking for 20K Data

In [15]:
df3 = df1.head(20000)

In [16]:
#Creating and the Feature and target Set for 10K Data
x2 = df3.iloc[:, :-1].values
y2 = df3.iloc[:, -1].values

In [17]:
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(x2, y2, test_size = 0.25, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train2 = sc.fit_transform(X_train2)
X_test2 = sc.transform(X_test2)

In [19]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train2, y_train2)

SVC(random_state=0)

In [20]:
y_pred2 = classifier.predict(X_test2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test2, y_pred2)
print(cm)
accuracy_score(y_test2, y_pred2)

[[4062    0]
 [  27  911]]


0.9946

## Checking for 40K Data

In [22]:
df4 = df1.head(40000)

In [23]:
df4

src_bytes  dst_bytes  count  diff_srv_rate  dst_host_srv_count  \
0            181       5450      8            0.0                   9   
1            239        486      8            0.0                  19   
2            235       1337      8            0.0                  29   
3            219       1337      6            0.0                  39   
4            217       2032      6            0.0                  49   
...          ...        ...    ...            ...                 ...   
39995      54540       8314      5            0.0                 255   
39996      54540       8314      6            0.0                 255   
39997      54540       8314      6            0.0                 255   
39998      54020       7300      7            0.0                 255   
39999      54540       8314      6            0.0                 255   

       dst_host_same_src_port_rate  label  
0                             0.11      0  
1                             0.05      0  
2                             0.03      0  
3                             0.03      0  
4                             0.02      0  
...                            ...    ...  
39995                         0.00      1  
39996                         0.00      1  
39997                         0.00      1  
39998                         0.00      1  
39999                         0.00      1  

[40000 rows x 7 columns]

In [24]:
#Creating and the Feature and target Set for 40K Data
x4 = df4.iloc[:, :-1].values
y4 = df4.iloc[:, -1].values

In [25]:
from sklearn.model_selection import train_test_split
X_train4, X_test4, y_train4, y_test4 = train_test_split(x4, y4, test_size = 0.25, random_state = 0)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train4 = sc.fit_transform(X_train4)
X_test4 = sc.transform(X_test4)

In [27]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train4, y_train4)

SVC(random_state=0)

In [28]:
y_pred4 = classifier.predict(X_test4)
print(np.concatenate((y_pred4.reshape(len(y_pred4),1), y_test4.reshape(len(y_test4),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test4, y_pred4)
print(cm)
accuracy_score(y_test4, y_pred4)

[[8929    5]
 [  49 1017]]


0.9946

In [30]:
data = {
    'Data_Size' : ['10K','20K','40K'],
    'Accuracy Score' : [0.9996 , 0.9946, 0.9946]
}

result_df2 = pd.DataFrame(data)
result_df2

Data_Size  Accuracy Score
0       10K          0.9996
1       20K          0.9946
2       40K          0.9946